apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
  namespace: local-dev
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location ~ / {
        proxy_pass http://app-service:3000;
      }
    }
