apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: local-dev
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb:10.6

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"

          volumeMounts:
            - name: mysql-persistent-volume
              mountPath: /var/lib/msyql

      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: mysql-pv-claim
