apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: local-dev
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-logs
      #   - name: nginx-config
      #     configMap:
      #       name: nginx-config-map

      containers:
        - name: nginx
          image: felipepaz/openresty:v1.0.28
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
            requests:
              memory: "32Mi"
              cpu: "100m"
          volumeMounts:
            - name: nginx-logs
              mountPath: /usr/local/openresty/nginx/logs

        - name: app-sidecar
          image: ubuntu:xenial
          command:
            - sh
            - -c
            - while true; do cat /usr/local/openresty/nginx/logs/access.log; sleep 1; done
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
            requests:
              memory: "32Mi"
              cpu: "100m"
          volumeMounts:
            - name: nginx-logs
              mountPath: /usr/local/openresty/nginx/logs
