apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: local-dev
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # volumes:
      #   - name: nginx-config
      #     configMap:
      #       name: nginx-config-map

      containers:
        - name: nginx
          image: felipepaz/openresty:v1.0.15
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
            requests:
              memory: "32Mi"
              cpu: "100m"
          # volumeMounts:
          #   - name: nginx-config
          #     mountPath: /etc/nginx/conf.d
