apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: local-dev
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: felipepaz/node-express:v2.0.0
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
            requests:
              memory: "32Mi"
              cpu: "100m"
            
